In [6]:
import pandas as pd
import numpy as np

arr_1 = np.arange(10, 51)
print(arr_1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [8]:
import numpy as np
arr_3 = np.random.rand(3, 3)
print(arr_3)

[[0.84752456 0.41640649 0.67222691]
 [0.6639727  0.74060199 0.81557714]
 [0.7435567  0.28215296 0.86869865]]


In [12]:

print(arr_3.shape)


(3, 3)


In [13]:
print(arr_3.size)

9


In [14]:
print(arr_3.dtype)

float64


In [18]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr+5)




[6 7 8 9]


In [19]:
import numpy as np
arr=np.array([[1,2],[3,4]])
arr1=np.array([[3,4],[5,6]])
print(arr*arr1)



[[ 3  8]
 [15 24]]


In [20]:
import numpy as np
array = np.arange(1, 26).reshape(5, 5)
first_row = array[0, :]
last_column = array[:, -1]
subarray = array[:3, :2]
print(first_row)
print(last_column)
print(subarray)



[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [25]:
import numpy as np
arr = np.random.randint(1, 101, 10)
max_value = np.max(arr)
min_value = np.min(arr)
mean_value = np.mean(arr)
std_value= np.std(arr)
print(arr)
print(max_value)
print(min_value)
print(mean_value)
print(std_value)




[30 56 83  3 64 49 70 52 49 99]
99
3
55.5
25.366316248127163


In [26]:
import numpy as np
arr = np.arange(1, 13)
mat= arr.reshape(3, 4)
print(mat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
import numpy as np
arr = np.ones((3, 3))
arr_1 = np.array([1, 2, 3])
print(arr+arr_1)



[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [31]:
import numpy as np
arr= np.random.randint(1, 51, 10)
div = arr[arr % 5 == 0]
print(arr)

print(div)

[ 4 28  2 20 26 41 44 49 43  3]
[20]


In [33]:
import numpy as np
mat1= np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat1, mat2))


[[19 22]
 [43 50]]


In [37]:
import numpy as np
arr= np.arange(1, 17).reshape(4, 4)
diag = arr[np.diag_indices(4)]
print(arr)
print(diag)



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  6 11 16]
